spring.application.name=ob-spring-security

spring.datasource.url=jdbc:postgresql://localhost:5432/users_database
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ob-secret-key
jwt.expiration=86400000